- src/test/java/com/basilisk/ApplicationTest.java
- Set Up UnitTest class for Application for example
> BASK3: Configuring The Test Environment

- src/main/java/com/basilisk/backend/models/Tweet.java
- src/main/java/com/basilisk/backend/repositories/TweetRepository.java
- src/main/java/com/basilisk/backend/services/TweetService.java
- created tweet object
- created tweet repository
- created tweet service
> BASK9: Initializing Tweet Object, Tweet Service and Tweet Repository

- src/main/java/com/basilisk/backend/models/FriendList.java
- src/main/java/com/basilisk/backend/repositories/FriendListRepository.java
- src/main/java/com/basilisk/backend/services/FriendListService.java
-Initialized the FriendList object
-Initialized the FriendList service
-Initialized the FriendList repository
> BASK10: Initializing Friends List Objects, Friends List Service, and Friends List Repository 

- src/main/java/com/basilisk/backend/services/FriendListService.java
BASK13
-created create method in FriendList Service
-created update method in FriendList Service
-created retrieve method in FriendList Service
-created delete method in FriendList Service
-Autowired the FriendList repository to FriendListService
> BASK13: CRUD for Friends List Service

- src/main/java/com/basilisk/backend/models/User.java
- src/main/java/com/basilisk/backend/services/UserService.java
BASK11 (Issue #14)
- Created CRUD operations in UserService
- Added toString for User Object
> BASK11 (Issue #14): CRUD for User Service

- pom.xml
- src/main/java/com/basilisk/backend/presenters/ProfilePresenter.java
BASK16 (issue #19):  
-created profile presenter class
-autowired tweet,user and friendList services
-added logging framework to pom.xml
-create sample update user method
> BASK16: Create Profile Presenter

- src/main/java/com/basilisk/frontend/views/HomePageView.java
BASK6 (Issue #9):
-Added tabs for Home, Profile
-Added Logout and Reload button
-Added search bar
-Added posts/tweets with their Like, Retweet, and Comment button
> BASK6: Prototype the Home Page

- src/main/java/com/basilisk/frontend/views/LoginView.java
BASK5(Issue #8):
-Created the LoginView page and added basic features necessary for a login page. Such as username and password fields as well as a login and sign up button.
> BASK5: Prototype the Login Page

- src/main/java/com/basilisk/frontend/views/ProfilePageView.java
-Added cover and profile picture
-Added user bio and information
> BASK7{Issue#10}:

- src/main/java/com/basilisk/frontend/views/ProfilePageView.java
Issue #10 
-Constants are now private and final
> BASK7: Prototype the Profile Page

- src/main/java/com/basilisk/backend/presenters/HomePresenter.java
- src/main/java/com/basilisk/backend/presenters/LoginPresenter.java
- src/main/java/com/basilisk/backend/presenters/ProfilePresenter.java
- src/main/java/com/basilisk/frontend/views/LoginView.java
- src/main/webapp/frontend/login-view.html
BASK31 (ISSUE #55 )
- Refactored the LoginView with HTML and CSS.
> BASK31: Refactor Login Page into a Complete UI

- src/main/java/com/basilisk/frontend/views/HomeView.java
- src/main/webapp/frontend/home-view.html
BASK32, Issue #56:
-Home and Profile tabs added using Vaadin Designer
-Logout and Reload button added using Vaadin Designer
-Search text box and Search button added using Vaadin Designer
-Added styles for background and buttons
> BASK32: Refactor Home Page into a Complete UI

- src/main/webapp/frontend/profile-view.html
BASK30(Issue #54): 
* Profile page refactored
> BASK30: Refactor Profile Page into a Complete UI

- pom.xml
- src/main/java/com/basilisk/frontend/components/MenuBarComponent.java
- src/main/java/com/basilisk/frontend/views/HomeView.java
- src/main/java/com/basilisk/frontend/views/ProfileView.java
- src/main/webapp/frontend/home-view.html
- src/main/webapp/frontend/login-view.html
- src/main/webapp/frontend/menu-bar-component.html
- src/main/webapp/frontend/profile-view.html
BASK33(Issue #69)
- New menu bar component for navigating and searching
- Added switching pages 
- Logout functionality
> BASK33: Navigating Pages & Logging Out

- src/main/java/com/basilisk/backend/presenters/LoginPresenter.java
- src/main/java/com/basilisk/backend/presenters/TweetPresenter.java
- src/main/java/com/basilisk/backend/services/UserService.java
- src/main/java/com/basilisk/frontend/components/TweetCreateComponent.java
- src/main/java/com/basilisk/frontend/components/TweetDisplayComponent.java
- src/main/java/com/basilisk/frontend/views/LoginView.java
BASK38(Issue #96)   
- Removed any UI or VaadinSession logic in LoginPresenter
- Removed any UI or VaadinSession logic in TweetPresenter
- Added logic back into Components and Views
> BASK38 - Refactor All Presenters to not have any UI or Vaadin Session

- pom.xml
- src/main/java/com/basilisk/backend/models/User.java
- src/main/java/com/basilisk/backend/services/CommentService.java
- src/main/java/com/basilisk/backend/services/FollowService.java
- src/main/java/com/basilisk/backend/services/RetweetService.java
- src/main/java/com/basilisk/backend/services/TweetService.java
- src/main/java/com/basilisk/backend/services/UserService.java
- src/test/java/com/basilisk/CrudTests.java
- src/test/java/com/basilisk/HomeTests.java
- src/test/java/com/basilisk/LoginTests.java
- src/test/java/com/basilisk/MenuBarTests.java
- src/test/java/com/basilisk/ProfileTests.java
- src/test/java/com/basilisk/Tests.java
- src/test/java/com/basilisk/TweetTests.java
BASK44(Issue #104)   
- Updated all tests to JUNIT 5
- Updated all Service Classes to have public methods to call all their crud operations
- Added platform runner dependency to properly run the tests
- Created 4 Unit Tests for CRUD operations of user
> BASK44: Unit Tests for CRUD for User

- src/test/java/com/basilisk/TweetTests.java
BASK41(Issue #101): 
* Added 4 new Unit Tests
* Like a tweet
* Dislike a tweet
* unLike a tweet
* unDislike a tweet
> BASK41 - Unit Tests for Liking and Disliking a Tweet

- src/test/java/com/basilisk/TweetTests.java
* Added two unit tests
* Check if tweets get posted if the text is empty
* Check if tweets get posted if the text exists
> BASK43 - Unit Tests for Posting Tweets

- src/test/java/com/basilisk/LoginTests.java
BASK40(Issue #100)   
- Created 6 Unit Tests for Logging in and Signing up
- Good Login, Bad Login, Empty Login
- Good Signup, Bad Signup, Empty Signup
> BASK40: Unit Tests for Login and Signing Up

- src/main/java/com/basilisk/backend/presenters/HomePresenter.java
- src/main/java/com/basilisk/backend/presenters/LoginPresenter.java
- src/main/java/com/basilisk/backend/presenters/MenuBarPresenter.java
- src/main/java/com/basilisk/backend/presenters/ProfilePresenter.java
- src/main/java/com/basilisk/backend/presenters/TweetPresenter.java
BASK46 (Issue#108)
-Autowired all the presenters with all services
> BASK46: All Presenters should have all Services

- src/main/java/com/basilisk/backend/models/Tweet.java
- src/test/java/com/basilisk/CrudTests.java
BASK45 (Issue #105):   
- Tweet:
- Added cloneable implementation
- CrudTests:
- Implemented create tweet test
- Implemented delete tweet test
- Implemented retrieve tweet test
- Implemented update tweet test
> BASK45 (Issue #105):

- src/main/java/com/basilisk/frontend/views/HomeView.java
- src/main/java/com/basilisk/frontend/views/LoginView.java
- src/main/java/com/basilisk/frontend/views/ProfileView.java
BASK61(ISSUE #133):
* Fixed the logic on when before entering pages, it would always call the init method even if there was no current user.
* All pages go properly to login when trying to access other URLS
> BASK61: Going to localhost:8080/profile while not logged in bug

- src/test/java/com/basilisk/CommentTests.java
> BASK51: Unit Tests for Commenting on a Tweet #115

- src/main/webapp/frontend/login-view.html
BASK59 (ISSUE #131):
-removed ../ from imports
-removed iron-form import
> BASK59: Fix Logout Bug

- src/main/java/com/basilisk/frontend/views/LoginView.java
-Users can no longer have whitespace in their username
> BASK57: Usernames should not be allowed to have spaces

- src/main/java/com/basilisk/backend/presenters/LoginPresenter.java
- src/test/java/com/basilisk/LoginTests.java
BASK58(Issue #122)
- Implemented password hashing using SHA-512 for security.
- Hash password before saving to database.
- Reverse hash password for user login password comparisons.
> BASK58: Securing Passwords

- src/main/java/com/basilisk/frontend/components/TweetDisplayComponent.java
- src/main/webapp/frontend/tweet-display-component.html
BASK 48, Issue #112
-Fixed hard coded comment button position
-Added code to make the comment button not change position when hiding comments button disappear
> BASK48: Hiding/Unhiding Comments

- src/test/java/com/basilisk/ProfileTests.java
BASK53(Issue #117):
- Created 2 Unit Tests for uploading images
- Unit test for uploading profile picture
- Unit test for uploading cover picture
> BASK53: Unit Tests for Changing Profile/Cover Photo

- src/main/java/com/basilisk/backend/presenters/TweetPresenter.java
- src/test/java/com/basilisk/RetweetTests.java
BASK50 (Issue #114):
- Created unit test for retweeting another user's tweet
- Created unit test for retweeting your own tweet
> BASK50: Unit Tests for Retweeting a Tweet

- src/test/java/com/basilisk/TweetTests.java
-Added two new unit tests for deleting tweets/retweets
> BASK55: Deleting Tweets Unit Tests

- src/test/java/com/basilisk/ProfileTests.java
BASK52 (ISSUE #116):
- non empty bio test
- empty bio test
> BASK52: Unit Tests for Editing Biography

- src/main/java/com/basilisk/frontend/components/CommentDisplayComponent.java
- src/main/java/com/basilisk/frontend/components/TweetDisplayComponent.java
- src/main/webapp/frontend/comment-display-component.html
- src/main/webapp/frontend/profile-view.html
- src/main/webapp/frontend/tweet-create-component.html
- src/main/webapp/frontend/tweet-display-component.html
BASK47 (ISSUE #111):
- Decorated the Components
> BASK47: Decorating the TweetDisplayComponent/CommentDisplayComponent
